{"name": "test_7[test-A while back I needed to count the amount]", "status": "failed", "statusDetails": {"message": "AssertionError: test failed\nassert ('test' == 'A while back...nt the amount'\n  - A while back I needed to count the amount\n  + test or 4 >= 20)", "trace": "self = <tests.test_negative.TestNegative object at 0x000001EF0789E220>, company_input = 'test', company_output = 'A while back I needed to count the amount'\n\n    @pytest.mark.parametrize(\"company_input, company_output\", [(\" \", \"A while back I needed to count the amount\"),\n                                                               (\"test\", \"A while back I needed to count the amount\")])\n    def test_7(self, company_input, company_output):\n        driver = self.driver\n        contact = ContactUs(driver)\n        contact.input_country(company_input)\n        count = len(company_input)\n>       assert company_input == company_output or count >= 20, \"test failed\"\nE       AssertionError: test failed\nE       assert ('test' == 'A while back...nt the amount'\nE         - A while back I needed to count the amount\nE         + test or 4 >= 20)\n\ntests\\test_negative.py:62: AssertionError"}, "parameters": [{"name": "company_input", "value": "'test'"}, {"name": "company_output", "value": "'A while back I needed to count the amount'"}], "start": 1634717901277, "stop": 1634717901378, "uuid": "e64bc52e-567a-4701-8436-f05e1919c688", "historyId": "382be3664b34c45421327dc39c8dfbe5", "testCaseId": "9e3c223828ff9f7ac56e0b738cfb08d3", "fullName": "tests.test_negative.TestNegative#test_7", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_negative"}, {"name": "subSuite", "value": "TestNegative"}, {"name": "host", "value": "SIS2W066"}, {"name": "thread", "value": "6828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_negative"}]}