{"name": "test_8[test-A while back I needed to count the amount]", "status": "failed", "statusDetails": {"message": "AssertionError: test failed\nassert ('test' == 'A while back...nt the amount'\n  - A while back I needed to count the amount\n  + test or 4 >= 180)", "trace": "self = <tests.test_negative.TestNegative object at 0x000001EF07859F70>, message_input = 'test', message_output = 'A while back I needed to count the amount'\n\n    @pytest.mark.parametrize(\"message_input, message_output\", [(\" \", \"A while back I needed to count the amount\"),\n                                                               (\"test\", \"A while back I needed to count the amount\")])\n    def test_8(self, message_input, message_output):\n        driver = self.driver\n        contact = ContactUs(driver)\n        contact.input_message(message_input)\n        count = len(message_input)\n>       assert message_input == message_output or count >= 180, \"test failed\"\nE       AssertionError: test failed\nE       assert ('test' == 'A while back...nt the amount'\nE         - A while back I needed to count the amount\nE         + test or 4 >= 180)\n\ntests\\test_negative.py:72: AssertionError"}, "parameters": [{"name": "message_input", "value": "'test'"}, {"name": "message_output", "value": "'A while back I needed to count the amount'"}], "start": 1634717918828, "stop": 1634717918930, "uuid": "3aecab0c-b88d-45fc-a83f-deb2bf22f19a", "historyId": "af07fc3986c5767fa3fe0063cb100ec0", "testCaseId": "d06cd45f7574d76eaa8ffd5067c0e12b", "fullName": "tests.test_negative.TestNegative#test_8", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('set_up')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_negative"}, {"name": "subSuite", "value": "TestNegative"}, {"name": "host", "value": "SIS2W066"}, {"name": "thread", "value": "6828-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_negative"}]}